CREATE TABLE public.users (
  id SERIAL PRIMARY KEY,
  name VARCHAR(50) NOT NULL,
  auth0_id VARCHAR(255) NOT NULL,
  phone VARCHAR(20), 
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  modified_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);